@startuml Overview

hide empty description

state Java {
    state Gui {
        state plot_section
        state text_commandos_section
        state error_section
    }
}

state Scala {
    state converter {
        state parser
        state draw_functions {
            state draw_boundingBox
            state drawLine
            state drawRectangle
            state drawCircle

            draw_boundingBox -[hidden]-> drawCircle
            drawLine -[hidden]-> draw_text
        }
    }
}

text_commandos_section -down-> parser: Text commandos
parser --> draw_functions: Commandos
parser -up-> error_section: Error messages
parser --> plot_section: text commandos
draw_functions -up-> plot_section: pixel data

@enduml


@startuml Sequence 
participant text_commandos_section
participant converter
participant parser
participant error_section
participant draw_functions
participant plot_section


text_commandos_section --> converter
converter --> parser
loop parse while no errors
    parser <--> draw_functions: Call: functions
end
alt error case
    converter --> error_section: Error messages
else
    converter --> plot_section: pixel data and text commandos
    
end

@enduml


@startuml Relationships
'skinparam linetype ortho
'!pragma layout smetana

package Java {
    file "GUI.java" as GUI_java {
        file GUI as GUI_ {
            class GUI {
            }
        }
    }

    file "utils.java" as utils_java {
        class ResultFromScala {
            ...
        }
    }
}


!definelong PixelsCanvas_methods()
    boundingBox(p1: Point, p2: Point, cmdId: Int): Unit
    line(command: Command, p1: Point, p2: Point, cmdId: Int): Unit
    rectangle(command: Command, p1: Point, p2: Point, cmdId: Int): Unit
    circle(command: Command, p1: Point, r: Float, cmdId: Int): Unit
    text(command: Command, p1: Point, text: String, cmdId: Int): Unit
!enddefinelong

package Scala {
    file "converter.scala" as converter_scala {
        object converter {
            pixelsCanvas: PixelsCanvas
            convert(commandos: String): ResultFromScala
        }
    }

    file "parser.scala" as parser_scala {
        object functions {
            parse(canvas: Canvas, str: String, defaultCommand: Command): ErrorOption

        }

        enum Command {
            draw(color: Color) 
            fill(color: Color)
        }

        class PixelsCanvas {
            ...
        }

        struct Point {
            x: Float
            y: Float
        }

        struct IntPoint {
            x: Int
            y: Int
        }

        interface Canvas {
            PixelsCanvas_methods()
        }
    }

    file "draw.scala" as draw_scala {
        object draw_functions {
            drawLine(command: Command, p1: IntPoint, p2: IntPoint): Map[(Int, Int), Color]
            drawRectangle(command: Command, p1: IntPoint, p2: IntPoint): Map[(Int, Int), Color]
            drawCircle(command: Command, p1: IntPoint, r: Int): Map[(Int, Int), Color]
        }
    }

    file "parserTest.scala" as parserTest_scala {
        class FakeCanvas {
            PixelsCanvas_methods()
        }
    }
}


FakeCanvas ..up..|> Canvas
PixelsCanvas ..|> Canvas

PixelsCanvas --up--> draw_functions
Canvas --> Point
PixelsCanvas --> Point
PixelsCanvas --> IntPoint
converter --> PixelsCanvas
functions --> Canvas
converter --up--> ResultFromScala
functions --> Command
converter --> functions
GUI ----down-> converter
GUI --> ResultFromScala

draw_functions --> IntPoint

@enduml

